# Connects to your local XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/wallet_sizing_dev
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# SDD 5.3: Simulating the ETL refresh
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-dev.sql
# Ensure tables are created before data is inserted
spring.jpa.defer-datasource-initialization=true
# The URL of your Identity Provider (AD / Keycloak / Azure)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://your-ad-server/auth/realms/master
# Or point directly to the JWK Set URI
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://your-ad-server/auth/realms/master/protocol/openid-connect/certs